In [1]:
import numpy as np
import pandas as pd

# Day 2

## Part 1: Inventory Management System

You stop falling through time, catch your breath, and check the screen on the device. "Destination reached. Current Year: 1518. Current Location: North Pole Utility Closet 83N10." You made it! Now, to find those anomalies.

Outside the utility closet, you hear footsteps and a voice. "...I'm not sure either. But now that so many people have chimneys, maybe he could sneak in that way?" Another voice responds, "Actually, we've been working on a new kind of **suit** that would let him fit through tight spaces like that. But, I heard that a few days ago, they lost the prototype fabric, the design plans, everything! Nobody on the team can even seem to remember important details of the project!"

"Wouldn't they have had enough fabric to fill several boxes in the warehouse? They'd be stored together, so the box IDs should be similar. Too bad it would take forever to search the warehouse for **two similar box IDs**..." They walk too far away to hear any more.

Late at night, you sneak to the warehouse - who knows what kinds of paradoxes you could cause if you were discovered - and use your fancy wrist device to quickly scan every box and produce a list of the likely candidates (your puzzle input).

To make sure you didn't miss any, you scan the likely candidate boxes again, counting the number that have an ID containing **exactly two of any letter** and then separately counting those with **exactly three of any letter**. You can multiply those two counts together to get a rudimentary *checksum* and compare it to what your device predicts.

For example, if you see the following box IDs:

- `abcdef` contains no letters that appear exactly two or three times.
- `bababc` contains two `a` and three `b`, so it counts for both.
- `abbcde` contains two `b`, but no letter appears exactly three times.
- `abcccd` contains three `c`, but no letter appears exactly two times.
- `aabcdd` contains two `a` and two `d`, but it only counts once.
- `abcdee` contains two `e`.
- `ababab` contains three `a` and three `b`, but it only counts once.

Of these box IDs, four of them contain a letter which appears exactly twice, and three of them contain a letter which appears exactly three times. Multiplying these together produces a checksum of `4 * 3 = 12`.

**What is the checksum** for your list of box IDs?


In [2]:
boxIds=pd.read_csv('boxIds.csv',names = ["id"])
testIds=pd.read_csv('testData.csv',names = ["id"])
ids = boxIds

In [3]:
ids['countTwice'] = 0
ids['countThrice'] = 0
ids

id  countTwice  countThrice
0    revtoubfniyhzsgxdowjwkqglp           0            0
1    revtcgbfniyhzsvxdomjwkqmlp           0            0
2    cevtcubfniyhqsgxdoakwkqmlp           0            0
3    revtcubfniyhzsgxdtavwkqmep           0            0
4    reutcuboniyhzmgxdoajwkqmlp           0            0
5    revtcubfniyhzsgxxqajmkqmlp           0            0
6    rwvtcvbfniyhzsgxdozjwkqmlp           0            0
7    qevtcbbfniyhzsgxdoljwkqmlp           0            0
8    rnvtcmbfniyhzsuxdoajwkqmlp           0            0
9    revtcubfsiyhzsgxdaaewkqmlp           0            0
10   revtcubfpiyhesgxhoajwkqmlp           0            0
11   revtcubfnivhzsuxdoljwkqmlp           0            0
12   retpcubwniyhzsgxdoajwkqmlp           0            0
13   revrcubfniyhzsgxdyajhkqmlp           0            0
14   revtcbbfniyhzsixdoajwvqmlp           0            0
15   revtcubfniyhzsgxdoanmkqmpp           0            0
16   jevtoubfnuyhzsgxdoajwkqmlp           0            0
17   rpwtcubfniehzsgxdoajwkqmlp           0            0
18   revhcubfniyhnsgxdoajwkxmlp           0            0
19   revtcubfniyhzswxdodjwkqvlp           0            0
20   reotcubfciyhzsgxdnajwkqmlp           0            0
21   revtcubfniyhzsgxdbatwsqmlp           0            0
22   rlvbcubfniyhzssxdoajwkqmlp           0            0
23   rentcubfnyyhzsgxdozjwkqmlp           0            0
24   revtcuufniyhasgxdohjwkqmlp           0            0
25   jevtcubfniyhxsgxdoajwkqwlp           0            0
26   ravtcubfnryhzfgxdoajwkqmlp           0            0
27   reltcubfnvyhzsgxdoajwkumlp           0            0
28   revtrubfnschzsgxdoajwkqmlp           0            0
29   uevtcubanichzsgxdoajwkqmlp           0            0
..                          ...         ...          ...
220  sevtcubfniynzsgxpoajwkqmlp           0            0
221  revtcnbfniyhzzgxdoajwzqmlp           0            0
222  revtcoofniyhzsgxdoajwkqmrp           0            0
223  revtcubfaiynysgxdoajwkqmlp           0            0
224  revtlubfniyizsnxdoajwkqmlp           0            0
225  revtcubfnwyzzsgxdoajwkqmzp           0            0
226  revtqubfjiyhzsgxdoajwkrmlp           0            0
227  revtaubfniyhpsgxdoajwkqilp           0            0
228  revncuufniwhzsgxdoajwkqmlp           0            0
229  revtcubfngyhisgxdoauwkqmlp           0            0
230  revtcubynqyhzdgxdoajwkqmlp           0            0
231  revtcubfniykzsgxdoyjwkqmla           0            0
232  revttubfniytzsghdoajwkqmlp           0            0
233  rerzcujfniyhzsgxdoajwkqmlp           0            0
234  revtcubtniydzsgxdoajwkpmlp           0            0
235  revecubfniyhzsvxsoajwkqmlp           0            0
236  revtcuvfniyhzsgsdaajwkqmlp           0            0
237  revtcubfniyxzsgxdoajtkzmlp           0            0
238  revtcukfxiyhzsgxdofjwkqmlp           0            0
239  revtcubfnayhzugxdqajwkqmlp           0            0
240  revtcbbfniyizsgxdoajwkqmop           0            0
241  revtcubfnzyhzsgxdoajwoqmpp           0            0
242  reitcnbfniyqzsgxdoajwkqmlp           0            0
243  rektcubfniyhzsgxdgijwkqmlp           0            0
244  revtcubfniyhpsaxdoajdkqmlp           0            0
245  ckvtcubfniyhzsgxeoajwkqmlp           0            0
246  revtcubfniyhzsgxdhajzknmlp           0            0
247  revscubfniyhrsgxdoajwwqmlp           0            0
248  revtcubfilyhzsgxdpajwkqmlp           0            0
249  fevtcubyniyhzsgxdoajwkqmpp           0            0

[250 rows x 3 columns]

In [97]:
for index, row in ids.iterrows():
    itemID=row['id']
    d = {}
    for c in itemID:
        if c in d:
            d[c] += 1
        else:
            d[c] = 1
    try:
        list(d.keys())[list(d.values()).index(2)]
        ids.at[index,'countTwice']=1
    except:
        ids.at[index,'countTwice']=0
    try:
        list(d.keys())[list(d.values()).index(3)]
        ids.at[index,'countThrice']=1
    except:
        ids.at[index,'countThrice']=0
        

In [98]:
checksum=ids.sum(axis=0)[1]*ids.sum(axis=0)[2]
checksum

6225


## Part 2

Confident that your list of box IDs is complete, you're ready to find the boxes full of prototype fabric.

The boxes will have IDs which differ by exactly one character at the same position in both strings. For example, given the following box IDs:

- `abcde`
- `fghij`
- `klmno`
- `pqrst`
- `fguij`
- `axcye`
- `wvxyz`

The IDs `abcde` and `axcye` are close, but they differ by two characters (the second and fourth). However, the IDs `fghij` and `fguij` differ by exactly one character, the third (`h` and `u`). Those must be the correct boxes.

What letters are common between the two correct box IDs? (In the example above, this is found by removing the differing character from either ID, producing `fgij`.)

In [4]:
def hamming_distance(s1, s2):
    return sum(ch1 != ch2 for ch1,ch2 in zip(s1,s2))

In [49]:
testIds=pd.read_csv('test2.csv',names = ["id"])
ids = boxIds
ids['hDist'] = 0

hDist=np.full((ids.shape[0],ids.shape[0]),np.inf)

In [50]:
hDist

array([[inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf],
       ...,
       [inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf],
       [inf, inf, inf, ..., inf, inf, inf]])

In [51]:
for i, row1 in ids.iterrows():
    for j, row2 in  ids.iterrows():
        if i == j or hDist[i,j]!=np.inf:
            continue;
        else:
            hd=hamming_distance(row1['id'],row2['id'])
            hDist[i,j]=hd
            hDist[j,i]=hd

In [52]:
hDist

array([[inf,  5.,  6., ...,  6.,  6.,  6.],
       [ 5., inf,  6., ...,  6.,  6.,  6.],
       [ 6.,  6., inf, ...,  5.,  6.,  5.],
       ...,
       [ 6.,  6.,  5., ..., inf,  6.,  6.],
       [ 6.,  6.,  6., ...,  6., inf,  6.],
       [ 6.,  6.,  5., ...,  6.,  6., inf]])

In [53]:
np.argwhere(hDist==1)

array([[ 63, 227],
       [227,  63]])

In [56]:
print (ids.loc[np.argwhere(hDist==1)[0,0],'id'])
print (ids.loc[np.argwhere(hDist==1)[0,1],'id'])

id1=ids.loc[np.argwhere(hDist==1)[0,0],'id']
id2=ids.loc[np.argwhere(hDist==1)[0,1],'id']

revtaubfniyhusgxdoajwkqilp
revtaubfniyhpsgxdoajwkqilp


In [68]:
packageId = list()
for i,char in enumerate(id1):
    if char == id2[i]:
        packageId.append(char)

In [69]:
''.join(packageId)

'revtaubfniyhsgxdoajwkqilp'